apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  type : ClusterIP
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
---
## --> Deployment configs <-- ##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: server:0.0.1-SNAPSHOT
          ports:
            - containerPort: 9090
          # will override the variable defined in docker container
          env:
            - name: JAVA_OPTS
              value: "-Dserver.port=8099"
          # config map configs details
          volumeMounts:
            - name: application-config
              mountPath: "/target/config"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: server-config
---